Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
